import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule],
  template: `
    <main>
      <h1>
        Little House in the Modern World
        <span class="subheading"
          >Bridging Generations with Timeless Lessons</span
        >
      </h1>
      <img
        src="../assets/laura.png"
        alt="Laura Ingalls on the prairie. Generated by: Dalle"
      />
      <p class="quote">
        “The real things haven't changed. It is still best to be honest and
        truthful; to make the most of what we have; to be happy with simple
        pleasures; and have courage when things go wrong.”
      </p>
      <p class="bold">— Laura Ingalls Wilder</p>
      <p class="bold">Welcome to Your Modern-Day Prairie</p>
      <p>
        Amid the bustling city streets and digital screens, lies a heart that
        yearns for simplicity, community, and a connection to the land. Here, at
        'Little House in the Modern World,' we combine the enduring lessons of
        the frontier with the necessities of today's world, guiding you to a
        balanced, fulfilling life.
      </p>
      <p class="bold">Discover with Us</p>
      <p>
        🌿 Modern Frontier Blog Dive into articles where prairie values meet
        modern challenges. Learn how to incorporate simplicity into your daily
        routine, foster a sense of community in a digital age, and connect with
        the earth even in urban settings.
      </p>
      <p>
        🍂 Heartland Workshops Embark on a journey of hands-on experiences. From
        crafting and canning to modern sustainable practices, we’re here to
        bridge the old and the new in captivating workshops that enrich the
        soul.
      </p>
      <p>
        📚 Book Club Revisit the tales of Laura Ingalls Wilder and explore
        contemporary literature that aligns with the frontier spirit. Engage in
        vibrant discussions, share perspectives, and rediscover the joy of
        stories that span generations.
      </p>
      <p class="bold">Join the Community</p>
      <p>
        Become a part of a movement that celebrates timeless values in a
        constantly evolving world. Share your stories, learn from others, and
        together let's build a community that cherishes the essence of the
        'Little House' spirit.
      </p>
      <p class="bold">Stay Updated</p>
      <p>
        Subscribe to our newsletter and never miss an article, workshop
        announcement, or book club session.
      </p>
      <div class="testimonials">
        <p class="bold">Testimonials</p>
        <p class="bold">
          "A breath of fresh prairie air in a digital age. This site has
          reconnected me to values I thought were lost in today's world." —
          Megan L.
        </p>

        <p class="bold">
          "The workshops are a delightful blend of old-world charm and modern
          practicality. Highly recommended!" — Carlos G.
        </p>
        <p class="bold">
          "Joining the book club was the best decision I made this year. The
          discussions are enriching and the community is welcoming." — Priya R.
        </p>
      </div>
      <p class="bold">Connect & Collaborate</p>
      <p>
        We're always eager to hear from you. Whether it's a story, an idea, or
        feedback, get in touch with us.
      </p>
    </main>
  `,
  styleUrls: ['./home.component.less'],
})
export class HomeComponent {}
